// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAizlQZLOZf4cIT5e2ZpWzceuMFhga1L4o',
    appId: '1:596409137513:web:fe5abbcd4145bb8ab3e5f8',
    messagingSenderId: '596409137513',
    projectId: 'mini-app-644e8',
    authDomain: 'mini-app-644e8.firebaseapp.com',
    storageBucket: 'mini-app-644e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwlBtQbdzjC3eS7OxS2TD2IRbgnhmyZs',
    appId: '1:596409137513:android:792ae64cea05f63bb3e5f8',
    messagingSenderId: '596409137513',
    projectId: 'mini-app-644e8',
    storageBucket: 'mini-app-644e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPU3kRgfa-k1ZGJxA568HWAhc_MMx_XXI',
    appId: '1:596409137513:ios:567b4f26eac4698eb3e5f8',
    messagingSenderId: '596409137513',
    projectId: 'mini-app-644e8',
    storageBucket: 'mini-app-644e8.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPU3kRgfa-k1ZGJxA568HWAhc_MMx_XXI',
    appId: '1:596409137513:ios:567b4f26eac4698eb3e5f8',
    messagingSenderId: '596409137513',
    projectId: 'mini-app-644e8',
    storageBucket: 'mini-app-644e8.firebasestorage.app',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAizlQZLOZf4cIT5e2ZpWzceuMFhga1L4o',
    appId: '1:596409137513:web:8b3ccdefeda97f9ab3e5f8',
    messagingSenderId: '596409137513',
    projectId: 'mini-app-644e8',
    authDomain: 'mini-app-644e8.firebaseapp.com',
    storageBucket: 'mini-app-644e8.firebasestorage.app',
  );
}
